name: pda_rfid_scanner
description: A Flutter plugin project for RFID scan on Blovedream PDA.
version: 0.0.1
homepage: https://github.com/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.pda_rfid_scanner
        pluginClass: PdaRfidScannerPlugin
