name: pda_rfid_scanner
description: A Flutter plugin project for RFID scan on Blovedream PDA devices. Uses Android sdk serialport. To communicate used MethodChannel and EventChannel.
version: 0.0.4
homepage: https://github.com/aaltynbek/pda_rfid_scanner

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.pda_rfid_scanner
        pluginClass: PdaRfidScannerPlugin
